# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    serializer:
        serialize_null: true
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
    routing_loader:
        default_format: 'json'
        include_format: false
    format_listener:
        rules:
            -
              path: '^/'
              priorities: ['json','html']
              fallback_format: 'json'
              prefer_extension: false
    view:
        view_response_listener: true
        formats:
            rss: false
            xml: false
            json: true
            jsonp: false
        mime_types:
            json: ['application/json; charset=UTF-8', 'application/json']
        templating_formats:
            html: false
        force_redirects:
            html: false
        failed_validation: 'HTTP_BAD_REQUEST'
        default_engine: 'twig'